### ISSUE TITLE
localization template advice

### ISSUE THREAD

**Issue by harukaxxxx** [Harvester62/stable-diffusion-webui-localization-it_IT#6]
I noticed that the this extension is actively ongoing, and there were some issues mentioned regarding the localization templates in the README file. If you are interested, here is the current maintained and updated repository for the localization templates ([stable-diffusion-webui-localization-source](https://github.com/harukaxxxx/stable-diffusion-webui-localization-source)).
For more inspiration on how to use them, you can refer to [stable-diffusion-webui-localization-zh_TW](https://github.com/harukaxxxx/stable-diffusion-webui-localization-zh_TW) or [stable-diffusion-webui-localization-ja_JP](https://github.com/AI-Creators-Society/stable-diffusion-webui-localization-ja_JP), both are working translation work on Crowdin platform.

**Comment by Harvester62** [comment]
Thank you for the suggestion. 
I will have for sure a look at the links you referenced to understand how this localization templates works. I have to understand if splitting the content of a single json file into hundreds of small json files, make sense because I then wouldn't be able to determine if a specific term has been already translated and how (thing that I can do now using a single file). If it can make my job easier I will consider it for sure.

**Comment by harukaxxxx** [comment]
Terms and duplicate keys can be handled very clearly by Crowdin if you want to :)
